---
title: "GCI-Java reaches the Cloud"
author: "Daniel Fireman (danielfireman@gmail.com)"
date: "March, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=F)
knitr::opts_chunk$set(warning=F)

require(gridExtra)
require(boot)
require(dplyr)
require(stringr)
require(cowplot)
require(ggplot2)

source("functions.R")

SAMPLE_SIZE <- 2500
RESAMPLES <- 1000
```

# Latency comparison

```{r}
al1.exp.gci.warm <- accesslog("1i", "gci_T80", 1)
al1.exp.nogci.warm <- accesslog("1i", "nogci_T80", 1)

al1.exp.gci <- filter(al1.exp.gci.warm, status == 200)
al1.exp.nogci <- filter(al1.exp.nogci.warm, status == 200)

print(paste("Number of succeeded requests (GCI ON): ", NROW(al1.exp.gci)))
print(paste("IQR (GCI ON): ", IQR(al1.exp.gci$request_time)))
summary(al1.exp.gci$request_time)
print(paste("Number of succeeded requests (GCI OFF): ", NROW(al1.exp.nogci)))
print(paste("IQR (GCI OFF): ", IQR(al1.exp.nogci$request_time)))
summary(al1.exp.nogci$request_time)
```

```{r, fig.asp=0.5, fig.align="center"}
# If you don't trim the library, your computer could die trying to resample.
al1.cmp <- rbind(
  data.frame("latency"=sample(al1.exp.gci$request_time, SAMPLE_SIZE), type="GCI ON"),
  data.frame("latency"=sample(al1.exp.nogci$request_time, SAMPLE_SIZE), type="GCI OFF"))

grid.arrange(
  ggplot(al1.cmp, aes(type, latency)) +
    geom_boxplot() +
    ggtitle("Summary") +
    ylab("Latency(ms)") +
    xlab("Type"),
   ggplot(al1.cmp, aes(latency, linetype=type)) +
    stat_ecdf() +
    ggtitle("ECDF") +
    xlab("Latency(ms)") +
    ylab("ECDF") +
    theme(legend.position="top"),
  ncol=2)

grid.arrange(
  ggplot(al1.cmp, aes(type, latency)) +
    stat_summary(fun.y=median, geom="point", shape=23, size=2) +
    stat_summary(fun.data=ci.median, geom="errorbar", width=0.05) +
    ggtitle("Median") +
    ylab("Latency(ms)") +
    xlab("Type"),
  ggplot(al1.cmp, aes(type, latency)) +
    stat_summary(fun.y=p99, geom="point", shape=23, size=2) +
    stat_summary(fun.data=ci.p99, geom="errorbar", width=0.05) +
    ggtitle("99 Percentile") +
    ylab("Latency(ms)") +
    xlab("Type"),
  ggplot(al1.cmp, aes(type, latency)) +
    stat_summary(fun.y=p999, geom="point", shape=23, size=2) +
    stat_summary(fun.data=ci.p999, geom="errorbar", width=0.05) +
    ggtitle("99.9 Percentile") +
    ylab("Latency(ms)") +
    xlab("Type"),
  ggplot(al1.cmp, aes(type, latency)) +
    stat_summary(fun.y=p9999, geom="point", shape=23, size=2) +
    stat_summary(fun.data=ci.p9999, geom="errorbar", width=0.05) +
    ggtitle("99.99 Percentile") +
    ylab("Latency(ms)") +
    xlab("Type"),
  ncol=2,
  nrow=2)
```

# Failed Requests

```{r}
failed.requests.gci <- filter(al1.exp.gci.warm, status == 503)
print(paste("Number of failed requests (GCI ON): ", NROW(failed.requests.gci), "(", (NROW(failed.requests.gci)/NROW(al1.exp.gci))*100, "% )"))
if (NROW(failed.requests.gci) > 0) {
  summary(failed.requests.gci$request_time)
  hist(failed.requests.gci$request_time)
}

failed.requests.nogci <- filter(al1.exp.nogci.warm, status == 503)
print(paste("Number of failed requests (GCI OFF): ", NROW(failed.requests.nogci), "(", (NROW(failed.requests.nogci)/NROW(al1.exp.nogci))*100, "% )"))
if (NROW(failed.requests.nogci) > 0) {
  summary(failed.requests.nogci$request_time)
  hist(failed.requests.nogci$request_time)
}
```

