---
title: "Scratchpad"
author: "Daniel Fireman (danielfireman@gmail.com)"
date: "June 18, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=F)
knitr::opts_chunk$set(warning=F)
knitr::opts_chunk$set(cache=F)

require(dplyr)
require(cowplot)
require(ggplot2)
require(rex)
library(grid)

source("functions.R")

REP <- 1
WARMUP_SECS <- 240
DURATION_SECS <- 0
```

# One Experiment

```{r}
percs.nogci.1i.state <- read.csv("1i/percs_nogci_T30_M262144_W500_1.csv")
percs.nogci.1i.state <- percs.nogci.1i.state %>% arrange(timestamp)
percs.nogci.1i.state$timestamp <- c(0, percs.nogci.1i.state$timestamp[2:NROW(percs.nogci.1i.state)]-percs.nogci.1i.state$timestamp[1])
percs.nogci.1i.state <- percs.nogci.1i.state %>% filter(timestamp >= 300 & timestamp <= 600)

nogci.1i.state <- accesslog("1i", "nogci_T30_M262144_W500", REP, WARMUP_SECS, DURATION_SECS) %>% na.omit()

# gc.nogci.1i.state <- scan("1i/gc_nogci_T30_M262144_W500_1_1.log", what = "character", sep = "\n") %>%
#   re_matches(
#     rex(
#       start,
#       "[", capture(name="timestamp", numbers),"ms]", anything, "->", capture(name="mem", numbers), "M", anything,
#       end
#     )
#   ) %>% mutate(timestamp=as.numeric(timestamp), mem=as.numeric(mem))
# gc.nogci.1i.state <- gc.nogci.1i.state %>% mutate(timestamp=timestamp/1000) %>% arrange(timestamp) %>% na.omit()
# gc.nogci.1i.state$timestamp <- c(0,gc.nogci.1i.state$timestamp[2:NROW(gc.nogci.1i.state)]-gc.nogci.1i.state$timestamp[1])
# gc.nogci.1i.state <- gc.nogci.1i.state %>% filter(timestamp >= 360 & timestamp <= 600)
```

```{r}
ggplot(data=percs.nogci.1i.state, aes(x=timestamp)) +
  geom_line(aes(y=p50_ms)) +
  geom_line(aes(y=p99_ms)) +
  xlab("Time") +
  ylab("Latency (ms)") +
  theme_minimal() +
  scale_y_continuous(breaks = seq(0, max(percs.nogci.1i.state$p99_ms), by = 10)) +
  coord_cartesian(ylim = c(0, max(percs.nogci.1i.state$p99_ms))) +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

```{r}
rt <- nogci.1i.state$succ$request_time
m <- median(rt)
p999 <- quantile(rt, c(0.999))
ggplot() +
  stat_ecdf(data=nogci.1i.state$succ, aes(request_time)) +
  ylab("Frequency") +
  xlab("Latency (ms)") +
  theme_minimal() +
  geom_vline(xintercept=m, size=0.8, linetype="dashed") +
  geom_text(aes(x=m, label="Median", y=0.35), vjust = 2, angle=90) +
  geom_vline(xintercept=p999, size=0.8, linetype="dashed") +
  geom_text(aes(x=p999, label="99.9th perc.", y=0.35), vjust = 2, angle=90) + 
  geom_segment(data=nogci.1i.state$succ, aes(x=m, y=0.1, xend=p999, yend=0.1), arrow = arrow(), size=0.1, colour="darkgray") +
  geom_segment(data=nogci.1i.state$succ, aes(x=p999, y=0.1, xend=m, yend=0.1), arrow = arrow(), size=0.1, colour="darkgray") +
  scale_x_continuous(breaks = seq(0, max(rt), by = 10)) +
  coord_cartesian(xlim = c(0, max(rt)))
ggsave("intro.pdf")
```